DEVICE : 'cuda'
SEED_VALUE : 4321
LOGDIR : ''
EXP_NAME : 'no'
DEBUG : True 
OUTPUT_DIR : 'results' 

DATASET_NAME : ''
ESTIMATOR : ''
BODY_REPRESENTATION : ''

SMPL_MODEL_DIR : "data/smpl/"

CUDNN :
  BENCHMARK : True
  DETERMINISTIC : False
  ENABLED : True

MODEL :
  d_word_vec: 128
  d_model: 128
  d_inner: 128
  n_layers: 4
  n_head: 4
  d_k: 64
  d_v: 64
  persons: 1

TRAIN :
  BATCH_SIZE : 2000
  WORKERS_NUM : 10
  EPOCH : 70
  LR : 0.001 
  LRDECAY : 0.96
  RESUME : None
  VALIDATE : True
  USE_6D_SMPL : True

EVALUATE :
  PRETRAINED : ''
  ROOT_RELATIVE : True
  SLIDE_WINDOW_STEP_SIZE : 1
LOSS :
  W_POS : 1.0
  W_ACCEL : 0.1
LOG :
  NAME : ''
# VIS :
#   END: 100
